import hashlib
import json
from dataclasses import asdict
from pathlib import Path

import cupy as cp
import numpy as np


class PhaseResponseBasis:
    """
    Exact full-field response basis for fixed-scene, phase-only training.

    Column r is the complete Helmholtz field generated by transducer r at its
    configured amplitude and zero phase. Online fields are reconstructed as
    G @ exp(1j * phases), without another PDE solve.
    """

    FORMAT_VERSION = 1

    def __init__(
        self,
        solver,
        storage_path: str,
        rhs_batch_size: int = 8,
        voxel_chunk_size: int = 262144,
        release_factor_after_build: bool = True,
    ):
        self.solver = solver
        self.storage_path = Path(storage_path)
        self.metadata_path = Path(f"{self.storage_path}.json")
        self.rhs_batch_size = int(rhs_batch_size)
        self.voxel_chunk_size = int(voxel_chunk_size)
        self.release_factor_after_build = bool(
            release_factor_after_build
        )
        self.dtype = np.dtype(np.complex128)
        self.basis = None
        self.basis_gpu = None
        self.completed_columns = 0
        self._mesh_hash_cache = None

        if self.rhs_batch_size < 1:
            raise ValueError("rhs_batch_size must be at least 1")
        if self.voxel_chunk_size < 1:
            raise ValueError("voxel_chunk_size must be at least 1")

    @property
    def num_transducers(self) -> int:
        return int(self.solver.transducers.num_transducers)

    @property
    def shape(self) -> tuple[int, int]:
        return self.solver.total_dofs, self.num_transducers

    @property
    def is_complete(self) -> bool:
        return self.completed_columns == self.num_transducers

    def build(self):
        backend = str(
            self.solver.cfg.solver.get("backend", "")
        ).lower()
        if backend != "cudss_hybrid_direct":
            raise ValueError(
                "phase_only training requires "
                "solver.backend='cudss_hybrid_direct'"
            )

        self.solver.assemble_matrix()
        dof_indices, emitter_ids = (
            self.solver.warp_engine.emitter_dof_map()
        )
        counts = np.bincount(
            emitter_ids,
            minlength=self.num_transducers,
        )
        missing = np.flatnonzero(counts == 0)
        if missing.size:
            raise ValueError(
                "The grid does not cover transducers "
                f"{missing.tolist()}"
            )

        self._open_or_create_storage()
        if self.is_complete:
            return self

        self.solver.factorize()
        amplitudes = self.solver.transducers.amplitudes
        for start in range(
            self.completed_columns,
            self.num_transducers,
            self.rhs_batch_size,
        ):
            stop = min(
                start + self.rhs_batch_size,
                self.num_transducers,
            )
            rhs = np.zeros(
                (self.solver.total_dofs, stop - start),
                dtype=np.complex128,
                order="F",
            )
            for emitter in range(start, stop):
                selected = emitter_ids == emitter
                rhs[
                    dof_indices[selected],
                    emitter - start,
                ] = amplitudes[emitter]

            self.basis[:, start:stop] = self.solver.solve_rhs(
                rhs,
                verbose=False,
            )
            self.basis.flush()
            self.completed_columns = stop
            self._write_metadata()

        if self.release_factor_after_build:
            self.solver.condensed_solver.close()
            self.solver.condensed_solver = None
        return self

    def to_gpu(self):
        self._require_complete()
        required = int(self.basis.nbytes)
        free_memory, _ = cp.cuda.Device(0).mem_info
        reserve = 256 * 1024**2
        if required + reserve > free_memory:
            raise MemoryError(
                "Insufficient GPU memory for phase response basis: "
                f"required={required / 1024**3:.2f} GiB, "
                f"free={free_memory / 1024**3:.2f} GiB"
            )
        self.basis_gpu = cp.asarray(self.basis)
        return self

    def release_gpu(self):
        self.basis_gpu = None

    def field(
        self,
        phases,
        return_numpy: bool = True,
    ):
        self._require_complete()
        phase_shape = tuple(phases.shape)
        if phase_shape != (self.num_transducers,):
            raise ValueError(
                f"phases must have shape ({self.num_transducers},), "
                f"got {phase_shape}"
            )

        if self.basis_gpu is not None:
            phase_gpu = cp.asarray(phases, dtype=cp.float64)
            weights = cp.exp(1j * phase_gpu)
            field = self.basis_gpu @ weights
            if return_numpy:
                field = cp.asnumpy(field)
        else:
            phase_array = np.asarray(phases, dtype=np.float64)
            weights = np.exp(1j * phase_array)
            field = self._chunked_matvec(weights)

        spatial_shape = (
            self.solver.cfg.domain.nx,
            self.solver.cfg.domain.ny,
            self.solver.cfg.domain.nz,
        )
        return field.reshape(spatial_shape, order="F")

    def phase_vjp(
        self,
        field_cotangent,
        phases,
        return_numpy: bool = True,
    ):
        """
        Compute dL/dphase for dL = Re(field_cotangent^H du).
        """
        self._require_complete()
        phase_shape = tuple(phases.shape)
        if phase_shape != (self.num_transducers,):
            raise ValueError(
                f"phases must have shape ({self.num_transducers},), "
                f"got {phase_shape}"
            )

        if self.basis_gpu is not None:
            cotangent = cp.asarray(
                field_cotangent,
                dtype=cp.complex128,
            ).reshape(-1, order="F")
            if cotangent.size != self.solver.total_dofs:
                raise ValueError("field_cotangent has the wrong size")
            response = self.basis_gpu.conjugate().transpose() @ cotangent
            weights = cp.exp(
                1j * cp.asarray(phases, dtype=cp.float64)
            )
            gradient = cp.real(
                cp.conjugate(response) * (1j * weights)
            )
            return cp.asnumpy(gradient) if return_numpy else gradient

        cotangent = np.asarray(
            field_cotangent,
            dtype=np.complex128,
        ).reshape(-1, order="F")
        if cotangent.size != self.solver.total_dofs:
            raise ValueError("field_cotangent has the wrong size")
        response = self._chunked_adjoint_matvec(cotangent)
        weights = np.exp(
            1j * np.asarray(phases, dtype=np.float64)
        )
        return np.real(
            np.conjugate(response) * (1j * weights)
        )

    def close(self):
        self.release_gpu()
        if isinstance(self.basis, np.memmap):
            self.basis.flush()
            memory_map = self.basis._mmap
            self.basis = None
            memory_map.close()

    def _open_or_create_storage(self):
        basis_exists = self.storage_path.exists()
        metadata_exists = self.metadata_path.exists()
        if basis_exists != metadata_exists:
            raise RuntimeError(
                "Phase basis data and metadata must exist together"
            )

        if basis_exists:
            metadata = json.loads(
                self.metadata_path.read_text(encoding="utf-8")
            )
            self._validate_metadata(metadata)
            self.basis = np.load(
                self.storage_path,
                mmap_mode="r+",
            )
            if self.basis.shape != self.shape:
                raise RuntimeError("Stored phase basis shape mismatch")
            if self.basis.dtype != self.dtype:
                raise RuntimeError("Stored phase basis dtype mismatch")
            self.completed_columns = int(
                metadata["completed_columns"]
            )
            return

        self.storage_path.parent.mkdir(parents=True, exist_ok=True)
        self.basis = np.lib.format.open_memmap(
            self.storage_path,
            mode="w+",
            dtype=self.dtype,
            shape=self.shape,
            fortran_order=False,
        )
        self.completed_columns = 0
        self._write_metadata()

    def _validate_metadata(self, metadata: dict):
        expected_shape = list(self.shape)
        if metadata.get("format_version") != self.FORMAT_VERSION:
            raise RuntimeError("Unsupported phase basis format version")
        if metadata.get("fingerprint") != self._fingerprint():
            raise RuntimeError(
                "Phase basis does not match the current physical scene"
            )
        if metadata.get("shape") != expected_shape:
            raise RuntimeError(
                f"Phase basis shape mismatch: {metadata.get('shape')} "
                f"!= {expected_shape}"
            )
        if metadata.get("dtype") != self.dtype.name:
            raise RuntimeError("Phase basis dtype mismatch")
        completed = int(metadata.get("completed_columns", -1))
        if completed < 0 or completed > self.num_transducers:
            raise RuntimeError("Invalid completed column count")

    def _write_metadata(self):
        metadata = {
            "format_version": self.FORMAT_VERSION,
            "fingerprint": self._fingerprint(),
            "shape": list(self.shape),
            "dtype": self.dtype.name,
            "completed_columns": self.completed_columns,
        }
        temporary = Path(f"{self.metadata_path}.tmp")
        temporary.write_text(
            json.dumps(metadata, indent=2, sort_keys=True),
            encoding="utf-8",
        )
        temporary.replace(self.metadata_path)

    def _fingerprint(self) -> str:
        cfg = self.solver.cfg
        payload = {
            "format_version": self.FORMAT_VERSION,
            "physics": asdict(cfg.physics),
            "transducer_specs": asdict(cfg.specs),
            "domain": asdict(cfg.domain),
            "boundary_conditions": cfg.boundary_conditions,
            "obstacles": cfg.obstacles,
            "mesh_content_sha256": self._mesh_content_hashes(),
            "amplitudes": self.solver.transducers.amplitudes.tolist(),
        }
        encoded = json.dumps(
            payload,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
        return hashlib.sha256(encoded).hexdigest()

    def _mesh_content_hashes(self) -> dict[str, str]:
        if self._mesh_hash_cache is not None:
            return self._mesh_hash_cache
        hashes = {}
        for obstacle in self.solver.cfg.obstacles:
            if obstacle.get("type", "").lower() != "mesh":
                continue
            path = Path(obstacle["file"])
            digest = hashlib.sha256()
            with path.open("rb") as mesh_file:
                for chunk in iter(lambda: mesh_file.read(1024 * 1024), b""):
                    digest.update(chunk)
            hashes[str(path)] = digest.hexdigest()
        self._mesh_hash_cache = hashes
        return hashes

    def _chunked_matvec(self, weights: np.ndarray) -> np.ndarray:
        result = np.empty(self.solver.total_dofs, dtype=np.complex128)
        for start in range(
            0,
            self.solver.total_dofs,
            self.voxel_chunk_size,
        ):
            stop = min(
                start + self.voxel_chunk_size,
                self.solver.total_dofs,
            )
            result[start:stop] = (
                self.basis[start:stop, :] @ weights
            )
        return result

    def _chunked_adjoint_matvec(
        self,
        vector: np.ndarray,
    ) -> np.ndarray:
        result = np.zeros(
            self.num_transducers,
            dtype=np.complex128,
        )
        for start in range(
            0,
            self.solver.total_dofs,
            self.voxel_chunk_size,
        ):
            stop = min(
                start + self.voxel_chunk_size,
                self.solver.total_dofs,
            )
            result += (
                self.basis[start:stop, :].conjugate().transpose()
                @ vector[start:stop]
            )
        return result

    def _require_complete(self):
        if self.basis is None or not self.is_complete:
            raise RuntimeError("Phase response basis is not complete")
